name: circuits-smoke

on:
  push:
    paths:
      - 'circuits/**'
      - '.github/workflows/circuits-smoke.yml'
  pull_request:
    paths:
      - 'circuits/**'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install repo deps
        run: |
          yarn install --frozen-lockfile

      - name: Reset Nx daemon
        run: |
          npx nx reset

      - name: Build shared library
        run: |
          npx nx run shared:build

      - name: Build circuits TypeScript
        working-directory: circuits
        run: |
          yarn build:ts

      - name: Run circuits setup to generate verification key
        working-directory: circuits
        run: |
          yarn setup

      - name: Verification key consistency check
        working-directory: circuits
        run: |
          # run the check to ensure zkey verification_key.json matches contract constants
          npx ts-node --files scripts/check-vk-onchain.ts

      - name: Run ZKP smoke test (lightweight)
        working-directory: circuits
        env:
          HOLDER_NAME: 'CI Test'
          LICENSE_NUMBER: 'CI000'
          EXAM_ID: 'CI_TEST'
          ACHIEVEMENT_LEVEL: 'Passed'
          ISSUED_DATE: '2024-01-01'
          EXPIRY_DATE: '2025-01-01'
          ISSUER: 'CI'
          HOLDER_DOB: '1990-01-01'
          NULLIFIER: '0x1'
          PRIVATE_KEY: '0x2'
        run: |
          # Run lightweight ZKP smoke test: generate proof only (no full setup/on-chain verify)
          echo "Running ZKP smoke test (lightweight)..."
          yarn ci-local:gen-proof
